name: Build and Test
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - uses: psf/black@stable

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --statistics

      - name: Lint with isort
        run: |
          isort .

      - name: Spell Check with codespell
        run: |
          codespell --skip="./.mypy_cache,./pytest_cache,.coverage,./htmlcov,./site,./.venv"

      - name: Lint with mypy
        run: |
          mypy

      - name: Test with pytest include Doc Test
        run: |
          pytest --cov --doctest-modules --cov-report html
